export default {
    UPDATE_TOKEN: "UPDATE_TOKEN",
    USER_DETAILS: "USER_DETAILS",
    USER_ID: "USER_ID",
    USER_LOGIN:"USER_LOGIN",
    CLEAR_DATA: 'CLEAR_DATA',
    USER_CREDS: 'USER_CREDS',

} 